//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TestingModel", "FK_tblAllot_tblProject", "tblProject", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Test.tblProject), "tblAllot", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Test.tblAllot), true)]
[assembly: EdmRelationshipAttribute("TestingModel", "FK_tblAllot_tblTester", "tblTester", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Test.tblTester), "tblAllot", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Test.tblAllot), true)]

#endregion

namespace Test
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TestingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TestingEntities object using the connection string found in the 'TestingEntities' section of the application configuration file.
        /// </summary>
        public TestingEntities() : base("name=TestingEntities", "TestingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestingEntities object.
        /// </summary>
        public TestingEntities(string connectionString) : base(connectionString, "TestingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestingEntities object.
        /// </summary>
        public TestingEntities(EntityConnection connection) : base(connection, "TestingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblAllot> tblAllots
        {
            get
            {
                if ((_tblAllots == null))
                {
                    _tblAllots = base.CreateObjectSet<tblAllot>("tblAllots");
                }
                return _tblAllots;
            }
        }
        private ObjectSet<tblAllot> _tblAllots;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblEmployee> tblEmployees
        {
            get
            {
                if ((_tblEmployees == null))
                {
                    _tblEmployees = base.CreateObjectSet<tblEmployee>("tblEmployees");
                }
                return _tblEmployees;
            }
        }
        private ObjectSet<tblEmployee> _tblEmployees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblProject> tblProjects
        {
            get
            {
                if ((_tblProjects == null))
                {
                    _tblProjects = base.CreateObjectSet<tblProject>("tblProjects");
                }
                return _tblProjects;
            }
        }
        private ObjectSet<tblProject> _tblProjects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTester> tblTesters
        {
            get
            {
                if ((_tblTesters == null))
                {
                    _tblTesters = base.CreateObjectSet<tblTester>("tblTesters");
                }
                return _tblTesters;
            }
        }
        private ObjectSet<tblTester> _tblTesters;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblAllots EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblAllots(tblAllot tblAllot)
        {
            base.AddObject("tblAllots", tblAllot);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblEmployees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblEmployees(tblEmployee tblEmployee)
        {
            base.AddObject("tblEmployees", tblEmployee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblProjects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblProjects(tblProject tblProject)
        {
            base.AddObject("tblProjects", tblProject);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTesters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTesters(tblTester tblTester)
        {
            base.AddObject("tblTesters", tblTester);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestingModel", Name="tblAllot")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblAllot : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblAllot object.
        /// </summary>
        /// <param name="alt_Id">Initial value of the Alt_Id property.</param>
        public static tblAllot CreatetblAllot(global::System.Int32 alt_Id)
        {
            tblAllot tblAllot = new tblAllot();
            tblAllot.Alt_Id = alt_Id;
            return tblAllot;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Alt_Id
        {
            get
            {
                return _Alt_Id;
            }
            set
            {
                if (_Alt_Id != value)
                {
                    OnAlt_IdChanging(value);
                    ReportPropertyChanging("Alt_Id");
                    _Alt_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Alt_Id");
                    OnAlt_IdChanged();
                }
            }
        }
        private global::System.Int32 _Alt_Id;
        partial void OnAlt_IdChanging(global::System.Int32 value);
        partial void OnAlt_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Pr_Id
        {
            get
            {
                return _Pr_Id;
            }
            set
            {
                OnPr_IdChanging(value);
                ReportPropertyChanging("Pr_Id");
                _Pr_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pr_Id");
                OnPr_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Pr_Id;
        partial void OnPr_IdChanging(Nullable<global::System.Int32> value);
        partial void OnPr_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Tst_Id
        {
            get
            {
                return _Tst_Id;
            }
            set
            {
                OnTst_IdChanging(value);
                ReportPropertyChanging("Tst_Id");
                _Tst_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tst_Id");
                OnTst_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Tst_Id;
        partial void OnTst_IdChanging(Nullable<global::System.Int32> value);
        partial void OnTst_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.String _Date;
        partial void OnDateChanging(global::System.String value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pst_Date
        {
            get
            {
                return _Pst_Date;
            }
            set
            {
                OnPst_DateChanging(value);
                ReportPropertyChanging("Pst_Date");
                _Pst_Date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pst_Date");
                OnPst_DateChanged();
            }
        }
        private global::System.String _Pst_Date;
        partial void OnPst_DateChanging(global::System.String value);
        partial void OnPst_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestingModel", "FK_tblAllot_tblProject", "tblProject")]
        public tblProject tblProject
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProject>("TestingModel.FK_tblAllot_tblProject", "tblProject").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProject>("TestingModel.FK_tblAllot_tblProject", "tblProject").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblProject> tblProjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProject>("TestingModel.FK_tblAllot_tblProject", "tblProject");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblProject>("TestingModel.FK_tblAllot_tblProject", "tblProject", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestingModel", "FK_tblAllot_tblTester", "tblTester")]
        public tblTester tblTester
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTester>("TestingModel.FK_tblAllot_tblTester", "tblTester").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTester>("TestingModel.FK_tblAllot_tblTester", "tblTester").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblTester> tblTesterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblTester>("TestingModel.FK_tblAllot_tblTester", "tblTester");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblTester>("TestingModel.FK_tblAllot_tblTester", "tblTester", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestingModel", Name="tblEmployee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblEmployee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblEmployee object.
        /// </summary>
        /// <param name="emp_SL">Initial value of the emp_SL property.</param>
        public static tblEmployee CreatetblEmployee(global::System.Int32 emp_SL)
        {
            tblEmployee tblEmployee = new tblEmployee();
            tblEmployee.emp_SL = emp_SL;
            return tblEmployee;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 emp_SL
        {
            get
            {
                return _emp_SL;
            }
            set
            {
                if (_emp_SL != value)
                {
                    Onemp_SLChanging(value);
                    ReportPropertyChanging("emp_SL");
                    _emp_SL = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("emp_SL");
                    Onemp_SLChanged();
                }
            }
        }
        private global::System.Int32 _emp_SL;
        partial void Onemp_SLChanging(global::System.Int32 value);
        partial void Onemp_SLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ep_Id
        {
            get
            {
                return _ep_Id;
            }
            set
            {
                Onep_IdChanging(value);
                ReportPropertyChanging("ep_Id");
                _ep_Id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ep_Id");
                Onep_IdChanged();
            }
        }
        private global::System.String _ep_Id;
        partial void Onep_IdChanging(global::System.String value);
        partial void Onep_IdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestingModel", Name="tblProject")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblProject : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblProject object.
        /// </summary>
        /// <param name="pr_Id">Initial value of the Pr_Id property.</param>
        public static tblProject CreatetblProject(global::System.Int32 pr_Id)
        {
            tblProject tblProject = new tblProject();
            tblProject.Pr_Id = pr_Id;
            return tblProject;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Pr_Id
        {
            get
            {
                return _Pr_Id;
            }
            set
            {
                if (_Pr_Id != value)
                {
                    OnPr_IdChanging(value);
                    ReportPropertyChanging("Pr_Id");
                    _Pr_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Pr_Id");
                    OnPr_IdChanged();
                }
            }
        }
        private global::System.Int32 _Pr_Id;
        partial void OnPr_IdChanging(global::System.Int32 value);
        partial void OnPr_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Domain
        {
            get
            {
                return _Domain;
            }
            set
            {
                OnDomainChanging(value);
                ReportPropertyChanging("Domain");
                _Domain = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Domain");
                OnDomainChanged();
            }
        }
        private global::System.String _Domain;
        partial void OnDomainChanging(global::System.String value);
        partial void OnDomainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestingModel", "FK_tblAllot_tblProject", "tblAllot")]
        public EntityCollection<tblAllot> tblAllots
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblAllot>("TestingModel.FK_tblAllot_tblProject", "tblAllot");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblAllot>("TestingModel.FK_tblAllot_tblProject", "tblAllot", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestingModel", Name="tblTester")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTester : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTester object.
        /// </summary>
        /// <param name="tst_Id">Initial value of the Tst_Id property.</param>
        public static tblTester CreatetblTester(global::System.Int32 tst_Id)
        {
            tblTester tblTester = new tblTester();
            tblTester.Tst_Id = tst_Id;
            return tblTester;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tst_Id
        {
            get
            {
                return _Tst_Id;
            }
            set
            {
                if (_Tst_Id != value)
                {
                    OnTst_IdChanging(value);
                    ReportPropertyChanging("Tst_Id");
                    _Tst_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Tst_Id");
                    OnTst_IdChanged();
                }
            }
        }
        private global::System.Int32 _Tst_Id;
        partial void OnTst_IdChanging(global::System.Int32 value);
        partial void OnTst_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adress
        {
            get
            {
                return _Adress;
            }
            set
            {
                OnAdressChanging(value);
                ReportPropertyChanging("Adress");
                _Adress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adress");
                OnAdressChanged();
            }
        }
        private global::System.String _Adress;
        partial void OnAdressChanging(global::System.String value);
        partial void OnAdressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mobile
        {
            get
            {
                return _Mobile;
            }
            set
            {
                OnMobileChanging(value);
                ReportPropertyChanging("Mobile");
                _Mobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mobile");
                OnMobileChanged();
            }
        }
        private global::System.String _Mobile;
        partial void OnMobileChanging(global::System.String value);
        partial void OnMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email_Id
        {
            get
            {
                return _Email_Id;
            }
            set
            {
                OnEmail_IdChanging(value);
                ReportPropertyChanging("Email_Id");
                _Email_Id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email_Id");
                OnEmail_IdChanged();
            }
        }
        private global::System.String _Email_Id;
        partial void OnEmail_IdChanging(global::System.String value);
        partial void OnEmail_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ep_Id
        {
            get
            {
                return _ep_Id;
            }
            set
            {
                Onep_IdChanging(value);
                ReportPropertyChanging("ep_Id");
                _ep_Id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ep_Id");
                Onep_IdChanged();
            }
        }
        private global::System.String _ep_Id;
        partial void Onep_IdChanging(global::System.String value);
        partial void Onep_IdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestingModel", "FK_tblAllot_tblTester", "tblAllot")]
        public EntityCollection<tblAllot> tblAllots
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblAllot>("TestingModel.FK_tblAllot_tblTester", "tblAllot");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblAllot>("TestingModel.FK_tblAllot_tblTester", "tblAllot", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
